language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
services:
  - postgresql
before_script:
  - cargo install diesel_cli
  - psql -c 'create database travisdb;' -U postgres
script:
  - diesel migration run
env:
  DATABASE_URL=postgres://postgres@localhost/travisdb
script:
  - cargo build --verbose --all