# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    curl -o rustup-init.sh https://sh.rustup.rs -sSf
    sh rustup-init.sh -y
  displayName: 'Install Rust'

- script: |
    sudo apt-get install libssl-dev=1.0.2g-1ubuntu4.13 libpq-dev -y --allow-downgrades
  displayName: 'Install Dependencies'

- script: |
    echo 'Agent ID $(Agent.Id)'
    echo 'Agent Name $(Agent.Name)'
    echo 'Agent MachineName $(Agent.MachineName)'
    echo 'Agent OS $(Agent.OS)'

    echo 'Build ID $(Build.BuildId)'
    echo 'Build Number $(Build.BuildNumber)'
  displayName: 'Print Info'

- script: |
    source $HOME/.cargo/env
    cargo build --release
  displayName: 'Build sushii'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'target/release/sushii'
    artifactName: 'sushii-$(Build.BuildNumber)-$(Agent.OS)'
