# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    curl -o rustup-init.sh https://sh.rustup.rs -sSf
    sh rustup-init.sh -y
    source $HOME/.cargo/env
    sudo apt-get install libpq-dev -y
    cargo build
  displayName: 'Build sushii'
